/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nipun Lakshitha
 */
public class Backup extends javax.swing.JFrame {

    /**
     * Creates new form Backup
     */
    String path = null;

    public Backup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backup = new javax.swing.JPanel();
        txtPath = new javax.swing.JTextField();
        btnBrows = new javax.swing.JButton();
        btnBackup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backup.setBackground(new java.awt.Color(106, 137, 204));
        backup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        backup.add(txtPath, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 360, -1));

        btnBrows.setBackground(new java.awt.Color(0, 51, 153));
        btnBrows.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrows.setForeground(new java.awt.Color(255, 255, 255));
        btnBrows.setText("Brows");
        btnBrows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsActionPerformed(evt);
            }
        });
        backup.add(btnBrows, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 130, 80, -1));

        btnBackup.setBackground(new java.awt.Color(0, 51, 255));
        btnBackup.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBackup.setForeground(new java.awt.Color(255, 255, 255));
        btnBackup.setText("BackUp");
        btnBackup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackupActionPerformed(evt);
            }
        });
        backup.add(btnBackup, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, -1, -1));

        getContentPane().add(backup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowsActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(this);
        String date = new SimpleDateFormat("YYYY-MM-dd").format(new Date());

        try {
            File file = fc.getSelectedFile();
            path = file.getAbsolutePath();
            path = path.replace('\\', '/');
            path = path + "_" + date + ".sql";

            txtPath.setText(path);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnBrowsActionPerformed

    private void btnBackupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackupActionPerformed
        Process p = null;
        if (txtPath.getText().trim().length() > 0) {
            try {
                Runtime runtime = Runtime.getRuntime();
                p = runtime.exec("C:/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe -uroot -proot --add-drop-database -B parts -r" + path);

                int processComplete = p.waitFor();

                if (processComplete == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Success");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Can't create backup");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ SELECT PATH");
        }
    }//GEN-LAST:event_btnBackupActionPerformed

    /**
         * @param args the command line arguments
         */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Backup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Backup().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backup;
    private javax.swing.JButton btnBackup;
    private javax.swing.JButton btnBrows;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}

