/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import com.sun.glass.events.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.MyProject.Controller.CustomerController;
import lk.ijse.MyProject.Model.CustomerModel;

/**
 *
 * @author Nipun Lakshitha
 */
public class newCustomer extends javax.swing.JFrame {

    /**
     * Creates new form newCustomer
     */
    public newCustomer() {
        initComponents();
        LoadAllCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        CustomerPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCustmoerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerPanel.setBackground(new java.awt.Color(106, 137, 204));
        CustomerPanel.setPreferredSize(new java.awt.Dimension(1060, 587));
        CustomerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Customer ID");
        CustomerPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, -1, -1));

        txtCustomerID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerIDKeyPressed(evt);
            }
        });
        CustomerPanel.add(txtCustomerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Customer Name");
        CustomerPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        txtCustmoerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustmoerNameKeyPressed(evt);
            }
        });
        CustomerPanel.add(txtCustmoerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Customer Address");
        CustomerPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        txtCustomerAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerAddressKeyPressed(evt);
            }
        });
        CustomerPanel.add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 200, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer Contact");
        CustomerPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, -1, -1));

        txtCustomerContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerContactActionPerformed(evt);
            }
        });
        txtCustomerContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCustomerContactKeyPressed(evt);
            }
        });
        CustomerPanel.add(txtCustomerContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 200, -1));

        CustomerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CstomerID", "Customer Name", "Customer Address", "Customer Contact"
            }
        ));
        CustomerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CustomerTable);

        CustomerPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 710, 140));

        jButton1.setBackground(new java.awt.Color(130, 204, 221));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(130, 204, 221)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        CustomerPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 580, 80, 40));

        jButton2.setBackground(new java.awt.Color(96, 163, 188));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(96, 163, 188)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        CustomerPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 80, 40));

        jButton3.setBackground(new java.awt.Color(60, 99, 130));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(60, 99, 130)));
        CustomerPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 570, 80, 40));

        jButton4.setBackground(new java.awt.Color(56, 173, 169));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Delete");
        jButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(56, 173, 169)));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        CustomerPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 570, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        CustomerPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Desktop\\Cfe9ap.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        CustomerPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerContactActionPerformed

    private void CustomerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerTableMouseClicked
        int rowIndex = CustomerTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
        txtCustomerID.setText(model.getValueAt(rowIndex, 0).toString());
        txtCustmoerName.setText(model.getValueAt(rowIndex, 1).toString());
        txtCustomerAddress.setText(model.getValueAt(rowIndex, 2).toString());
        txtCustomerContact.setText(model.getValueAt(rowIndex, 3).toString());
    }//GEN-LAST:event_CustomerTableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtCustomerID.getText().trim().length() > 0 && txtCustmoerName.getText().length() > 0 && txtCustomerAddress.getText().length() > 0 && txtCustomerContact.getText().length() > 0) {
            String CusID = txtCustomerID.getText();
            String CusName = txtCustmoerName.getText();
            String CusAddress = txtCustomerAddress.getText();
            int CusContact = Integer.parseInt(txtCustomerContact.getText());
            boolean detail = false;
            detail = new CustomerController().AddCustomer(new CustomerModel(CusID, CusName, CusAddress, CusContact));
            if (detail == true) {
                JOptionPane.showMessageDialog(rootPane, "IS ADDED");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not ADDED");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "INSERT ALL DETAILS");
        }
        LoadAllCustomer();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (txtCustomerID.getText().trim().length() > 0) {
            String CusID = txtCustomerID.getText();
            String CusName = txtCustmoerName.getText();
            String CusAddress = txtCustomerAddress.getText();
            int CusContact = Integer.parseInt(txtCustomerContact.getText());
            boolean update = false;

            update = new CustomerController().UpdateCustomer(new CustomerModel(CusID, CusName, CusAddress, CusContact));
            if (update == true) {
                JOptionPane.showMessageDialog(rootPane, "Update");
            } else {
                JOptionPane.showMessageDialog(rootPane, "try");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ INSERT ITEM ID");
        }
        LoadAllCustomer();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (txtCustomerID.getText().trim().length() > 0) {
            String CusID = txtCustomerID.getText();
            boolean delete = false;

            delete = new CustomerController().CustomerDelete(CusID);
            if (delete == true) {
                JOptionPane.showMessageDialog(rootPane, "Deleted");
            } else {
                JOptionPane.showMessageDialog(rootPane, "try");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ INSERT ITEM ID");
        }
        LoadAllCustomer();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (txtCustomerID.getText().trim().length() > 0) {
            String id = txtCustomerID.getText();
            for (CustomerModel detail : new CustomerController().SearchCustomer(id)) {
                txtCustmoerName.setText(detail.getCusName());
                txtCustomerAddress.setText(detail.getCusAddress());
                txtCustomerContact.setText(Integer.toString(detail.getCusContact()));
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtCustomerIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIDKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        txtCustmoerName.requestFocus();
        }
    }//GEN-LAST:event_txtCustomerIDKeyPressed

    private void txtCustmoerNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustmoerNameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
        txtCustomerAddress.requestFocus();
        }
    }//GEN-LAST:event_txtCustmoerNameKeyPressed

    private void txtCustomerAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerAddressKeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
       txtCustomerContact.requestFocus();
       }
    }//GEN-LAST:event_txtCustomerAddressKeyPressed

    private void txtCustomerContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerContactKeyPressed
        char c=evt.getKeyChar();
        if(Character.isLetter(c)){
        txtCustomerContact.setEditable(false);
        }else{
        txtCustomerContact.setEditable(true);
        }
    }//GEN-LAST:event_txtCustomerContactKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JTable CustomerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCustmoerName;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerContact;
    private javax.swing.JTextField txtCustomerID;
    // End of variables declaration//GEN-END:variables

    private void LoadAllCustomer() {

        DefaultTableModel model = (DefaultTableModel) CustomerTable.getModel();
        model.setRowCount(0);

        for (CustomerModel cus : new CustomerController().getAllCustomer()) {
            model.addRow(new Object[]{cus.getCusID(), cus.getCusName(), cus.getCusAddress(), cus.getCusContact()});
        }

    }
}
