/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.MyProject.Controller.ItemReturnController;
import lk.ijse.MyProject.Model.ItemReturnModel;
import lk.ijse.MyProject.Model.OrderDetailModel;

/**
 *
 * @author Nipun Lakshitha
 */
public class newItemReturn extends javax.swing.JFrame {

    /**
     * Creates new form newItemReturn
     */
    public newItemReturn() {
        initComponents();
        LoadDateTime();
        LoadIRID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtItemID = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtQTY = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIRID = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReturnTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        OrderTable = new javax.swing.JTable();
        txtTime = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(106, 137, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("OrderID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, -1, 20));
        jPanel1.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 140, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Return Date");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, -1, -1));

        txtDate.setEnabled(false);
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Item Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));
        jPanel1.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Return Time");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 110, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("ItemID");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
        jPanel1.add(txtItemID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 140, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("QTY");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, -1));
        jPanel1.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 120, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("IR ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        txtIRID.setEnabled(false);
        jPanel1.add(txtIRID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 140, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Enter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 100, 40));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Rest");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 210, 100, 40));

        ReturnTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IRID", "Order ID", "Item ID", "Item Name", "QTY", "Pricel"
            }
        ));
        jScrollPane2.setViewportView(ReturnTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 770, 120));

        OrderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderID", "ItemID", "QTY", "Unit Price", "Discount", "Price"
            }
        ));
        jScrollPane1.setViewportView(OrderTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 770, 110));

        txtTime.setEnabled(false);
        jPanel1.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 120, -1));

        jButton1.setText("ADD TO SHOP");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 540, 100, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        String id = txtOrderId.getText().toString();
        DefaultTableModel model = (DefaultTableModel) OrderTable.getModel();
        model.setRowCount(0);

        for (OrderDetailModel detail : new ItemReturnController().getAllDdetails(id)) {
            model.addRow(new Object[]{detail.getOrderID(), detail.getItemID(), detail.getQTY(), detail.getUnitPrice(), detail.getDiscount(), detail.getPrice()});
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        String id = txtItemID.getText();
        String name = new ItemReturnController().getItemName(id);
        txtItemName.setText(name);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) ReturnTable.getModel();

        String id = txtItemID.getText();
        double price = new ItemReturnController().getItemUnitPrice(id);
        double qty = Double.parseDouble(txtQTY.getText());

        double tot = qty * price;

        int rowIndex = isAlreadyExits(txtItemID.getText());

        if (rowIndex == -1) {
            Object[] rowData = {txtIRID.getText(), txtOrderId.getText(), txtItemID.getText(), txtItemName.getText(), qty, tot};
            model.addRow(rowData);
        } else {
            qty += (double) model.getValueAt(rowIndex, 4);
            tot = qty * price;
            model.setValueAt(qty, rowIndex, 4);
            model.setValueAt(tot, rowIndex, 5);

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        txtItemName.setText("");
        txtItemID.setText("");
        txtQTY.setText("");
        txtOrderId.setText("");
        txtQTY.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newItemReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newItemReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newItemReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newItemReturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newItemReturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable OrderTable;
    private javax.swing.JTable ReturnTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtIRID;
    private javax.swing.JTextField txtItemID;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtTime;
    // End of variables declaration//GEN-END:variables

    private void LoadDateTime() {
        Date date = new Date();

        SimpleDateFormat format1 = new SimpleDateFormat("YYYY-MM-dd");
        txtDate.setText(format1.format(date));

        SimpleDateFormat format2 = new SimpleDateFormat("HH:mm:ss");
        txtTime.setText(format2.format(date));
    }

    private void LoadIRID() {
        String id = new ItemReturnController().getIRID();
        if (id != null) {
            String[] temp = id.split("R");
            int tempNo = Integer.parseInt(temp[1]);
            tempNo += 1;

            if (tempNo < 10) {
                txtIRID.setText("IR00" + tempNo);
            } else if (tempNo < 100) {
                txtIRID.setText("IR0" + tempNo);
            } else {
                txtIRID.setText("IR" + tempNo);
            }

        } else {
            txtIRID.setText("IR001");
        }
    }

    private int isAlreadyExits(String text) {
         DefaultTableModel model = (DefaultTableModel) ReturnTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            String temp = ReturnTable.getValueAt(i, 2).toString();

            if (temp.equalsIgnoreCase(text)) {
                return i;
            }
        }
        return -1;
    }
}
