/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.MyProject.Controller.SupplierController;
import lk.ijse.MyProject.Model.supplier;

/**
 *
 * @author Nipun Lakshitha
 */
public class newSupplier extends javax.swing.JFrame {

    /**
     * Creates new form newSupplier
     */
    public newSupplier() {
        initComponents();
        LoadAllSupplier();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupplierPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSuppllierEmail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtSupplierContact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupplierTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtSupplierName = new javax.swing.JTextField();
        btnSupSave = new javax.swing.JButton();
        btnSupUpdate = new javax.swing.JButton();
        btnSupDelete = new javax.swing.JButton();
        btnSupClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SupplierPanel.setBackground(new java.awt.Color(106, 137, 204));
        SupplierPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Supplier ID");
        SupplierPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, 20));
        SupplierPanel.add(txtSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 229, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Supplier Address");
        SupplierPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));
        SupplierPanel.add(txtSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 229, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Supplier Email");
        SupplierPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));
        SupplierPanel.add(txtSuppllierEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 229, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Supplier Contact");
        SupplierPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        txtSupplierContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierContactKeyPressed(evt);
            }
        });
        SupplierPanel.add(txtSupplierContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 229, -1));

        SupplierTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier Name", "Supplier ID", "Supplier Adddress", "Supplier Email", "Supplier Contact"
            }
        ));
        SupplierTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SupplierTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(SupplierTable);

        SupplierPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 710, 90));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Supplier Name");
        SupplierPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, -1));
        SupplierPanel.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 229, 20));

        btnSupSave.setBackground(new java.awt.Color(130, 204, 221));
        btnSupSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSupSave.setText("Save");
        btnSupSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(130, 204, 221)));
        btnSupSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupSaveActionPerformed(evt);
            }
        });
        SupplierPanel.add(btnSupSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 540, 80, 40));

        btnSupUpdate.setBackground(new java.awt.Color(96, 163, 188));
        btnSupUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnSupUpdate.setText("Update");
        btnSupUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupUpdateActionPerformed(evt);
            }
        });
        SupplierPanel.add(btnSupUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, -1, 40));

        btnSupDelete.setBackground(new java.awt.Color(60, 99, 130));
        btnSupDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnSupDelete.setText("Delete");
        btnSupDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(60, 99, 130)));
        btnSupDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupDeleteActionPerformed(evt);
            }
        });
        SupplierPanel.add(btnSupDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 81, 40));

        btnSupClear.setBackground(new java.awt.Color(56, 173, 169));
        btnSupClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSupClear.setForeground(new java.awt.Color(255, 255, 255));
        btnSupClear.setText("Clear");
        btnSupClear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(56, 173, 169)));
        btnSupClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupClearActionPerformed(evt);
            }
        });
        SupplierPanel.add(btnSupClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 81, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SupplierPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SupplierPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierContactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierContactKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtSupplierContact.setEditable(false);
        } else {
            txtSupplierContact.setEditable(true);
        }
    }//GEN-LAST:event_txtSupplierContactKeyPressed

    private void SupplierTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SupplierTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
        int rowIndex = SupplierTable.getSelectedRow();

       
        txtSupplierName.setText(model.getValueAt(rowIndex, 0).toString());
         txtSupplierId.setText(model.getValueAt(rowIndex, 1).toString());
        txtSupplierAddress.setText(model.getValueAt(rowIndex, 2).toString());
        txtSuppllierEmail.setText(model.getValueAt(rowIndex, 3).toString());
        txtSupplierContact.setText(model.getValueAt(rowIndex, 4).toString());
    }//GEN-LAST:event_SupplierTableMouseClicked

    private void btnSupSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupSaveActionPerformed
        String supplierName = txtSupplierName.getText();
        String supplierID = txtSupplierId.getText();
        int contact = Integer.parseInt(txtSupplierContact.getText());
        String address = txtSupplierAddress.getText();
        String email = txtSuppllierEmail.getText();

        boolean detail = new SupplierController().AddItem(new supplier(supplierName, supplierID, contact, address, email));

        if (detail == true) {
            JOptionPane.showMessageDialog(rootPane, "Suucess");
        } else {
            JOptionPane.showMessageDialog(rootPane, "try");
        }
        LoadAllSupplier();
    }//GEN-LAST:event_btnSupSaveActionPerformed

    private void btnSupUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupUpdateActionPerformed
        String supplierName = txtSupplierName.getText();
        String supplierID = txtSupplierId.getText();
        int contact = Integer.parseInt(txtSupplierContact.getText());
        String address = txtSupplierAddress.getText();
        String email = txtSuppllierEmail.getText();
        boolean detail = new SupplierController().UpdateItem(new supplier(supplierName, supplierID, contact, address, email));
        if (detail == true) {
            JOptionPane.showMessageDialog(rootPane, "Suucess");
        } else {
            JOptionPane.showMessageDialog(rootPane, "try");
        }
        DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();

        LoadAllSupplier();
    }//GEN-LAST:event_btnSupUpdateActionPerformed

    private void btnSupDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupDeleteActionPerformed
        boolean delete = new SupplierController().DeleteSupplier(txtSupplierId.getText().toString());

        if (delete == true) {
            JOptionPane.showMessageDialog(rootPane, "DELETED");
        } else {
            JOptionPane.showMessageDialog(rootPane, "try");
        }
        LoadAllSupplier();
    }//GEN-LAST:event_btnSupDeleteActionPerformed

    private void btnSupClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupClearActionPerformed

    }//GEN-LAST:event_btnSupClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newSupplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newSupplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SupplierPanel;
    private javax.swing.JTable SupplierTable;
    private javax.swing.JButton btnSupClear;
    private javax.swing.JButton btnSupDelete;
    private javax.swing.JButton btnSupSave;
    private javax.swing.JButton btnSupUpdate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierContact;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSuppllierEmail;
    // End of variables declaration//GEN-END:variables

    private void LoadAllSupplier() {
        DefaultTableModel model = (DefaultTableModel) SupplierTable.getModel();
        model.setRowCount(0);
        for (supplier sup : new SupplierController().getAllSupplier()) {
            model.addRow(new Object[]{sup.getSupplierName(), sup.getSupplierID(), sup.getAddress(), sup.getEmail(), sup.getContact()});
        }
    }
}
