/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.MyProject.Controller.SupBillController;
import lk.ijse.MyProject.Model.ItemModel;
import lk.ijse.MyProject.Model.SupBillModel;

/**
 *
 * @author Nipun Lakshitha
 */
public class newSupBill extends javax.swing.JFrame {

   

   

    /**
     * Creates new form newSupBill
     */
    public newSupBill() {
        initComponents();
        LoadDateTime();
        LoardLogin();
        getBillID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SupBillPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtBillNo = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtSupplierUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtBillDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSupID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSupName = new javax.swing.JTextField();
        txtQTY = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblItemId1 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrice = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SupTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SupBillPanel.setBackground(new java.awt.Color(106, 137, 204));
        SupBillPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Supplier Bill No");
        SupBillPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));

        txtBillNo.setEnabled(false);
        SupBillPanel.add(txtBillNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 140, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("User");
        SupBillPanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        txtSupplierUser.setEnabled(false);
        SupBillPanel.add(txtSupplierUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date");
        SupBillPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, -1, -1));

        txtBillDate.setEnabled(false);
        txtBillDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBillDateActionPerformed(evt);
            }
        });
        SupBillPanel.add(txtBillDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 80, 130, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Time");
        SupBillPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        txtTime.setEnabled(false);
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });
        SupBillPanel.add(txtTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 140, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Supplier ID");
        SupBillPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, -1, -1));
        SupBillPanel.add(txtSupID, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, 100, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        SupBillPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Supplier Name");
        SupBillPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, -1, -1));
        SupBillPanel.add(txtSupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 130, 130, -1));

        txtQTY.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQTYKeyPressed(evt);
            }
        });
        SupBillPanel.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, 130, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("QTY");
        SupBillPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 180, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        SupBillPanel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, -1, -1));
        SupBillPanel.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 140, -1));

        lblItemId1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblItemId1.setText("Item ID");
        SupBillPanel.add(lblItemId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        txtItemName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtItemName.setText("Item Name");
        SupBillPanel.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price");
        SupBillPanel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, -1, -1));

        txtPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPriceActionPerformed(evt);
            }
        });
        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPriceKeyPressed(evt);
            }
        });
        SupBillPanel.add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 140, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        SupBillPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        SupBillPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 270, 160, -1));

        SupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Item ID", "Item Name", "QTY", "Unit Price", "price"
            }
        ));
        jScrollPane1.setViewportView(SupTable);

        SupBillPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 780, 180));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("ToTAL");
        SupBillPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 560, -1, -1));
        SupBillPanel.add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 203, -1));

        jButton4.setBackground(new java.awt.Color(255, 0, 51));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("pay");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        SupBillPanel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 540, 200, 60));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cancel");
        SupBillPanel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 140, 30));
        SupBillPanel.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 150, -1));

        getContentPane().add(SupBillPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBillDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBillDateActionPerformed

    }//GEN-LAST:event_txtBillDateActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       // new SupBillSearch(this).setVisible(true);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void txtQTYKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQTYKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtQTY.setEditable(false);
        } else {
            txtQTY.setEditable(true);
        }
    }//GEN-LAST:event_txtQTYKeyPressed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        //new ItemSearch(this).setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void txtPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPriceActionPerformed

    private void txtPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            txtPrice.setEditable(false);
        } else {
            txtPrice.setEditable(true);
        }
    }//GEN-LAST:event_txtPriceKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (txtQTY.getText().trim().length() > 0 && txtPrice.getText().trim().length() > 0) {
            DefaultTableModel model = (DefaultTableModel) SupTable.getModel();

            double qty = Double.parseDouble(txtQTY.getText());
            double price = Double.parseDouble(txtPrice.getText());
            double tot = qty * price;

            int RowIndex = isAlreadyExits(txtId.getText());

            if (RowIndex == -1) {
                model.addRow(new Object[]{txtSupID.getText(), txtSupName.getText(), txtId.getText(), txtName.getText(), qty, price, tot});
            } else {
                qty += (double) model.getValueAt(RowIndex, 4);
                tot = qty * price;
                SupTable.setValueAt(tot, RowIndex, 5);
                SupTable.setValueAt(qty, RowIndex, 4);
            }
            calculateTotal();
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ ENTER QTY AND PRICE");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtId.setText("");
        txtName.setText("");
        txtSupID.setText("");
        txtSupName.setText("");
        txtQTY.setText("");
        txtPrice.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String billNo = txtBillNo.getText();
        String date=txtBillDate.getText();
        List<SupBillModel> list = new ArrayList<>();
        DefaultTableModel model = (DefaultTableModel) SupTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {

            String SupID = model.getValueAt(i, 0).toString();
            String ItemID = model.getValueAt(i, 2).toString();
            double qty = Double.parseDouble(model.getValueAt(i, 4).toString());
            double unitprice = Double.parseDouble(model.getValueAt(i, 5).toString());
            double payment = Double.parseDouble(model.getValueAt(i, 6).toString());

            list.add(new SupBillModel(billNo, SupID,date, ItemID, qty, unitprice, payment));
        }
        boolean isAded = new SupBillController().AddToDB(list);

        if (isAded) {
            JOptionPane.showMessageDialog(rootPane, "isAded");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Not Aded");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newSupBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newSupBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newSupBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newSupBill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newSupBill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SupBillPanel;
    private javax.swing.JTable SupTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lblItemId1;
    private javax.swing.JTextField txtBillDate;
    private javax.swing.JTextField txtBillNo;
    private static javax.swing.JTextField txtId;
    private static javax.swing.JLabel txtItemName;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtSupID;
    private javax.swing.JTextField txtSupName;
    private javax.swing.JTextField txtSupplierUser;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private int isAlreadyExits(String text) {
        DefaultTableModel model = (DefaultTableModel) SupTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            String temp = model.getValueAt(i, 2).toString();
            if (temp.equalsIgnoreCase(text)) {
                return i;
            }
        }
        return -1;
    }

    private void calculateTotal() {
        DefaultTableModel model = (DefaultTableModel) SupTable.getModel();
        double temp = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            temp += (double) SupTable.getValueAt(i, 6);
        }
        txtTotal.setText(Double.toString(temp));
    }

    void setSupValue(String supID) {
        txtSupID.setText(supID);
    }

    void setSupName(String supName) {
        txtSupName.setText(supName);
    }

    void SetValue(String itemId) {
        txtId.setText(itemId);
    }

    void SetItemName(String itemName) {
        txtName.setText(itemName);
    }

    private void LoadDateTime() {
        Date date = new Date();

        SimpleDateFormat format = new SimpleDateFormat("YYYY-MM-dd");
        txtBillDate.setText(format.format(date));

        SimpleDateFormat format1 = new SimpleDateFormat("HH:mm:ss");
        txtTime.setText(format1.format(date));
    }

    private void LoardLogin() {
        //   txtSupplierUser.setText(Login.LoginUser.toString());
    }

    private void getBillID() {
        String BillNo = new SupBillController().getSupBill();

        if (BillNo != null) {
            String[] temp = BillNo.split("P");
            int temNo = Integer.parseInt(temp[1]);
            temNo++;
            if (temNo < 10) {
                txtBillNo.setText("SP00" + temNo);
            } else if (temNo < 100) {
                txtBillNo.setText("SP0" + temNo);
            } else {
                txtBillNo.setText("SP" + temNo);
            }
        } else {
            txtBillNo.setText("SP001");
        }
    }
}
