/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import javax.swing.JOptionPane;
import lk.ijse.MyProject.Controller.UserDetailController;
import lk.ijse.MyProject.Model.UserDetailModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nipun Lakshitha
 */
public class newUserDetail extends javax.swing.JFrame {

    /**
     * Creates new form newUserDetail
     */
    public newUserDetail() {
        initComponents();
        LoadUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newUserDeatilPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUserNIC = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUserAddress = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        UserTable = new javax.swing.JTable();
        txtUserContact = new javax.swing.JTextField();
        btnUserSave = new javax.swing.JButton();
        btnUserUpdate = new javax.swing.JButton();
        btnUserDelete = new javax.swing.JButton();
        btnUserClear = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        newUserDeatilPanel.setBackground(new java.awt.Color(106, 137, 204));
        newUserDeatilPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("UserID");
        newUserDeatilPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, 30));
        newUserDeatilPanel.add(txtUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 170, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Name");
        newUserDeatilPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, -1, 30));
        newUserDeatilPanel.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 170, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("N.I.C");
        newUserDeatilPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, 30));
        newUserDeatilPanel.add(txtUserNIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Address");
        newUserDeatilPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, -1, 30));
        newUserDeatilPanel.add(txtUserAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 170, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Contact");
        newUserDeatilPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, 30));

        UserTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Name", "N.I.C", "Address", "Contact"
            }
        ));
        UserTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UserTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(UserTable);

        newUserDeatilPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, 700, 90));

        txtUserContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserContactActionPerformed(evt);
            }
        });
        newUserDeatilPanel.add(txtUserContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 170, -1));

        btnUserSave.setBackground(new java.awt.Color(130, 204, 221));
        btnUserSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUserSave.setForeground(new java.awt.Color(255, 255, 255));
        btnUserSave.setText("Save");
        btnUserSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(130, 204, 221)));
        btnUserSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserSaveActionPerformed(evt);
            }
        });
        newUserDeatilPanel.add(btnUserSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 70, 40));

        btnUserUpdate.setBackground(new java.awt.Color(96, 163, 188));
        btnUserUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUserUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUserUpdate.setText("Update");
        btnUserUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(96, 163, 188)));
        btnUserUpdate.setPreferredSize(new java.awt.Dimension(35, 19));
        btnUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserUpdateActionPerformed(evt);
            }
        });
        newUserDeatilPanel.add(btnUserUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 70, 40));

        btnUserDelete.setBackground(new java.awt.Color(56, 173, 169));
        btnUserDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUserDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnUserDelete.setText("Delete");
        btnUserDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(56, 173, 169)));
        btnUserDelete.setPreferredSize(new java.awt.Dimension(35, 23));
        btnUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDeleteActionPerformed(evt);
            }
        });
        newUserDeatilPanel.add(btnUserDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 543, 70, 40));

        btnUserClear.setBackground(new java.awt.Color(60, 99, 130));
        btnUserClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUserClear.setForeground(new java.awt.Color(255, 255, 255));
        btnUserClear.setText("Clear");
        btnUserClear.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(60, 99, 130)));
        newUserDeatilPanel.add(btnUserClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 540, 70, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nipun Lakshitha\\Downloads\\serchSmall.png")); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        newUserDeatilPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, 40, -1));

        getContentPane().add(newUserDeatilPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserContactActionPerformed

    private void btnUserSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserSaveActionPerformed
        if (txtUserID.getText().trim().length() > 0 && txtUserName.getText().trim().length() > 0 && txtUserAddress.getText().trim().length() > 0 && txtUserContact.getText().trim().length() > 0 && txtUserNIC.getText().trim().length() > 0) {
            String name = txtUserName.getText();
            String ID = txtUserID.getText();
            String NIC = txtUserNIC.getText();
            String Address = txtUserAddress.getText();
            int Contact = Integer.parseInt(txtUserContact.getText());

            boolean isSave = new UserDetailController().SaveUser(new UserDetailModel(name, NIC, Address, Contact, ID));

            if (isSave) {
                JOptionPane.showMessageDialog(rootPane, "isSave");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not Save");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Insert All Details");
        }
        LoadUser();
    }//GEN-LAST:event_btnUserSaveActionPerformed

    private void btnUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserUpdateActionPerformed
        if (txtUserID.getText().trim().length() > 0) {
            String name = txtUserName.getText();
            String ID = txtUserID.getText();
            String NIC = txtUserNIC.getText();
            String Address = txtUserAddress.getText();
            int Contact = Integer.parseInt(txtUserContact.getText());

            boolean isUpdate = new UserDetailController().UpdateUser(new UserDetailModel(name, NIC, Address, Contact, ID));

            if (isUpdate) {
                JOptionPane.showMessageDialog(rootPane, "IS Update");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not Update");
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ Insert UserID");
        }
        LoadUser();
    }//GEN-LAST:event_btnUserUpdateActionPerformed

    private void UserTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UserTableMouseClicked
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();

        int rowIndex = UserTable.getSelectedRow();

        txtUserID.setText(model.getValueAt(rowIndex, 0).toString());
        txtUserName.setText(model.getValueAt(rowIndex, 1).toString());
        txtUserNIC.setText(model.getValueAt(rowIndex, 2).toString());
        txtUserAddress.setText(model.getValueAt(rowIndex, 3).toString());
        txtUserContact.setText(model.getValueAt(rowIndex, 4).toString());
    }//GEN-LAST:event_UserTableMouseClicked

    private void btnUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDeleteActionPerformed
        if (txtUserID.getText().trim().length() > 0) {
            String id = txtUserID.getText();
            boolean isDelete = new UserDetailController().DeleteUser(id);

            if (isDelete) {
                JOptionPane.showMessageDialog(rootPane, "Is Deletd");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Not deleted");
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "PLZ Insert UserID");
        }
        LoadUser();
    }//GEN-LAST:event_btnUserDeleteActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         if (txtUserID.getText().trim().length() > 0) {
             String id=txtUserID.getText();
            for(UserDetailModel detail:new UserDetailController().SerchUser(id)){
            txtUserName.setText(detail.getName());
            txtUserNIC.setText(detail.getNIC());
            txtUserAddress.setText(detail.getAddress());
            txtUserContact.setText(Integer.toString(detail.getContact()));
            }
         }
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newUserDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newUserDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable UserTable;
    private javax.swing.JButton btnUserClear;
    private javax.swing.JButton btnUserDelete;
    private javax.swing.JButton btnUserSave;
    private javax.swing.JButton btnUserUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel newUserDeatilPanel;
    private javax.swing.JTextField txtUserAddress;
    private javax.swing.JTextField txtUserContact;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserNIC;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    private void LoadUser() {
        DefaultTableModel model = (DefaultTableModel) UserTable.getModel();
        model.setRowCount(0);

        for (UserDetailModel User : new UserDetailController().getUserDetail()) {
            model.addRow(new Object[]{User.getUserID(), User.getName(), User.getNIC(), User.getAddress(), User.getContact()});
        }
    }
}
