/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.MyProject.view;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import lk.ijse.MyProject.Controller.MonthlyIncomeController;
import lk.ijse.MyProject.Controller.OrderController;
import lk.ijse.MyProject.Model.ReportModel;

/**
 *
 * @author Nipun Lakshitha
 */
public class Report extends javax.swing.JFrame {

    /**
     * Creates new form Report
     */
    public Report() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel65 = new javax.swing.JLabel();
        txtFromYear = new javax.swing.JTextField();
        txtFromMonth = new javax.swing.JTextField();
        txtFromDate = new javax.swing.JTextField();
        jLabel66 = new javax.swing.JLabel();
        jLabel67 = new javax.swing.JLabel();
        jLabel68 = new javax.swing.JLabel();
        jLabel69 = new javax.swing.JLabel();
        jLabel70 = new javax.swing.JLabel();
        txtToYear = new javax.swing.JTextField();
        jLabel77 = new javax.swing.JLabel();
        txtToMonth = new javax.swing.JTextField();
        jLabel78 = new javax.swing.JLabel();
        txtToDate = new javax.swing.JTextField();
        ReportPanel = new javax.swing.JPanel();
        jLabel71 = new javax.swing.JLabel();
        txtRportFromYear = new javax.swing.JTextField();
        txtRportFromMonth = new javax.swing.JTextField();
        txtRportFromDate = new javax.swing.JTextField();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        txtRportToYear = new javax.swing.JTextField();
        jLabel79 = new javax.swing.JLabel();
        txtRportToMonth = new javax.swing.JTextField();
        jLabel80 = new javax.swing.JLabel();
        txtRportToDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ReportTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel65.setText("Year From");

        txtFromYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFromYearKeyPressed(evt);
            }
        });

        txtFromMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFromMonthKeyPressed(evt);
            }
        });

        txtFromDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFromDateKeyPressed(evt);
            }
        });

        jLabel66.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel66.setForeground(new java.awt.Color(204, 204, 204));
        jLabel66.setText("YYYY");

        jLabel67.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel67.setForeground(new java.awt.Color(204, 204, 204));
        jLabel67.setText("MM");

        jLabel68.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel68.setForeground(new java.awt.Color(204, 204, 204));
        jLabel68.setText("DD");

        jLabel69.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel69.setText("Year To");

        jLabel70.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel70.setForeground(new java.awt.Color(204, 204, 204));
        jLabel70.setText("YYYY");

        txtToYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToYearKeyPressed(evt);
            }
        });

        jLabel77.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel77.setForeground(new java.awt.Color(204, 204, 204));
        jLabel77.setText("MM");

        txtToMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtToMonthKeyPressed(evt);
            }
        });

        jLabel78.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel78.setForeground(new java.awt.Color(204, 204, 204));
        jLabel78.setText("DD");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReportPanel.setBackground(new java.awt.Color(106, 137, 204));
        ReportPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel71.setText("Year From");
        ReportPanel.add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        txtRportFromYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRportFromYearKeyPressed(evt);
            }
        });
        ReportPanel.add(txtRportFromYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 90, -1));

        txtRportFromMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRportFromMonthKeyPressed(evt);
            }
        });
        ReportPanel.add(txtRportFromMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 50, -1));

        txtRportFromDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRportFromDateKeyPressed(evt);
            }
        });
        ReportPanel.add(txtRportFromDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 50, -1));

        jLabel72.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel72.setForeground(new java.awt.Color(204, 204, 204));
        jLabel72.setText("YYYY");
        ReportPanel.add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 40, -1));

        jLabel73.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel73.setForeground(new java.awt.Color(204, 204, 204));
        jLabel73.setText("MM");
        ReportPanel.add(jLabel73, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 20, -1));

        jLabel74.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel74.setForeground(new java.awt.Color(204, 204, 204));
        jLabel74.setText("DD");
        ReportPanel.add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 20, -1));

        jLabel75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel75.setText("Year To");
        ReportPanel.add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jLabel76.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel76.setForeground(new java.awt.Color(204, 204, 204));
        jLabel76.setText("YYYY");
        ReportPanel.add(jLabel76, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 40, -1));

        txtRportToYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRportToYearKeyPressed(evt);
            }
        });
        ReportPanel.add(txtRportToYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 90, -1));

        jLabel79.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel79.setForeground(new java.awt.Color(204, 204, 204));
        jLabel79.setText("MM");
        ReportPanel.add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 30, -1));

        txtRportToMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtRportToMonthKeyPressed(evt);
            }
        });
        ReportPanel.add(txtRportToMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 50, -1));

        jLabel80.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel80.setForeground(new java.awt.Color(204, 204, 204));
        jLabel80.setText("DD");
        ReportPanel.add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 20, -1));
        ReportPanel.add(txtRportToDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 50, -1));

        ReportTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Name", "Item ID", "QTY"
            }
        ));
        jScrollPane1.setViewportView(ReportTable);

        ReportPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, 610, 100));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ReportPanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Clear");
        ReportPanel.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, -1));

        getContentPane().add(ReportPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFromYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFromMonth.requestFocus();
        }
    }//GEN-LAST:event_txtFromYearKeyPressed

    private void txtFromMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromMonthKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtFromDate.requestFocus();
        }
    }//GEN-LAST:event_txtFromMonthKeyPressed

    private void txtFromDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFromDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtToYear.requestFocus();
        }
    }//GEN-LAST:event_txtFromDateKeyPressed

    private void txtToYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtToMonth.requestFocus();
        }
    }//GEN-LAST:event_txtToYearKeyPressed

    private void txtToMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtToMonthKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtToDate.requestFocus();
        }
    }//GEN-LAST:event_txtToMonthKeyPressed

    private void txtRportFromYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRportFromYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
           txtRportFromMonth.requestFocus();
        }
    }//GEN-LAST:event_txtRportFromYearKeyPressed

    private void txtRportFromMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRportFromMonthKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtRportFromDate.requestFocus();
        }
    }//GEN-LAST:event_txtRportFromMonthKeyPressed

    private void txtRportFromDateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRportFromDateKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtRportToYear.requestFocus();
        }
    }//GEN-LAST:event_txtRportFromDateKeyPressed

    private void txtRportToYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRportToYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtRportToMonth.requestFocus();
        }
    }//GEN-LAST:event_txtRportToYearKeyPressed

    private void txtRportToMonthKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRportToMonthKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txtRportToDate.requestFocus();
        }
    }//GEN-LAST:event_txtRportToMonthKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String from = txtRportFromYear.getText() + "-" + txtRportFromMonth.getText() + "-" + txtRportFromDate.getText();
        String to = txtRportToYear.getText() + "-" + txtRportToMonth.getText() + "-" + txtRportToDate.getText();
        
        DefaultTableModel model=(DefaultTableModel) ReportTable.getModel();
        model.setRowCount(0);
        for(ReportModel detail:new OrderController().getReport(from,to)){
        model.addRow(new Object[]{detail.getItemName(),detail.getItemID(),detail.getQTY()});
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Report.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ReportPanel;
    private javax.swing.JTable ReportTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel65;
    private javax.swing.JLabel jLabel66;
    private javax.swing.JLabel jLabel67;
    private javax.swing.JLabel jLabel68;
    private javax.swing.JLabel jLabel69;
    private javax.swing.JLabel jLabel70;
    private javax.swing.JLabel jLabel71;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtFromDate;
    private javax.swing.JTextField txtFromMonth;
    private javax.swing.JTextField txtFromYear;
    private javax.swing.JTextField txtRportFromDate;
    private javax.swing.JTextField txtRportFromMonth;
    private javax.swing.JTextField txtRportFromYear;
    private javax.swing.JTextField txtRportToDate;
    private javax.swing.JTextField txtRportToMonth;
    private javax.swing.JTextField txtRportToYear;
    private javax.swing.JTextField txtToDate;
    private javax.swing.JTextField txtToMonth;
    private javax.swing.JTextField txtToYear;
    // End of variables declaration//GEN-END:variables
}
